# Generated by Django 4.1.3 on 2023-03-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contactdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("country", models.CharField(max_length=200, verbose_name="country")),
                (
                    "email",
                    models.EmailField(default="", max_length=30, verbose_name="email"),
                ),
                ("contact", models.IntegerField(default="", verbose_name="contact")),
                (
                    "message",
                    models.TextField(
                        default="", max_length=300, verbose_name="message"
                    ),
                ),
            ],
        ),
    ]
